version: '3'

services:
    rabbit:
        build: ./rabbitmq
        image: myrabbit
        ports: 
            - 5672:5672
            - 15672:15672
    demoapi:
        build: ./demoapi
        image: demoapi
        ports:
            - 8080:80
        depends_on: 
            - "rabbit"
    nodejsapi:
        build: ./nodejsapi
        image: nodejsapi
        ports:
            - 5000:5000
    emailservice:
        build: ./emailservice
        image: emailservice
        depends_on: 
            - "rabbit"
    mail:
        image: mailhog/mailhog
        ports:
            - 1025:1025
            - 8025:8025
#    mailer:
#        build: .
#        environment:
#            - MAILER_SMTP_SERVER_HOST=mailhog
#			- MAILER_SMTP_SERVER_PORT=1025





#  https://www.nuget.org/packages/DockerDemo_Messages/1.0.0