version: '2'

services:
    rabbit:
        #build: ./rabbitmq
        image: myrabbit
        ports: 
            - 5672:5672
    demoapi:
        #build: ./demoapi
        image: demoapi
        ports:
            - 8080:80
    nodejsapi:
        #build: ./nodejsapi
        image: nodejsapi
        ports:
            - 5000:5000
#	mailhog:
#        image: mailhog/mailhog
#        ports:
#            - 1025:1025
#            - 8025:8025
#    mailer:
#        build: .
#        environment:
#            - MAILER_SMTP_SERVER_HOST=mailhog
#			- MAILER_SMTP_SERVER_PORT=1025